version: "3.1"
services:
    redis:
      container_name: redis-queue-redis
      image: redis:alpine
      restart: always

    webserver:
      container_name: redis-queue-nginx
      image: nginx:alpine
      restart: always
      working_dir: /var/www/redis-queue
      volumes:
          - .:/var/www/redis-queue
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"

    php-fpm:
      container_name: redis-queue-php-fpm
      build: docker/php-fpm
      restart: always
      working_dir: /var/www/redis-queue
      volumes:
        - .:/var/www/redis-queue
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
